### ISSUE TITLE
The payment window does not work a multi language shop

### ISSUE THREAD

**Issue by Scan-Drink** [onpayio/php-sdk#29]
How to handle a multi language shop (eg. Danish / English)?

Payment window language appears to be locked by the "Payment window language" setting in the back office.
It would be more appropriate that language in the payment window was determined by the current language in the front office so that it follows the language chosen by the customer.

**Comment by emilstahl** [comment]
Hi @Scan-Drink 

It seems like your shop is running on Prestahsop.

This issue should be created in the [prestashop repo](https://github.com/onpayio/prestashop).

Thanks!

**Comment by Scan-Drink** [comment]
@emilstahl 

I am very sorry. 
I'm totally new with github.
Can't you explain exactly where to post these bugs?

**Comment by emilstahl** [comment]
@Scan-Drink No problem.

In the prestashop repo I linked. Direct link to create a new issue: https://github.com/onpayio/prestashop/issues/new
