### ISSUE TITLE
Backwards incompatible change in patch

### ISSUE THREAD

**Issue by HenriksenTeamBlue** [onpayio/php-sdk#31]
In 1.0.6 or 1.0.7 \OnPay\OnPayAPI now throws an exception if gateway_id is blank or 0.  This was not the case in 1.0.5.

We have fixed the dependency local, but backwards incompatible changes should only be introduced in major versions, not patch or minor updates.

**Comment by dvaeversted** [comment]
I do not agree that this is a back incompatible change, since providing a blank or 0 id has always been unsupported.
The gateway_id is still optional aswell, but if the setting is set we now throw an exception early to signify this where as it was previous undefined what the behaviour would be.
