### ISSUE TITLE
Refreshing token

### ISSUE THREAD

**Issue by JeppeDonslund** [onpayio/php-sdk#32]
I can only use the code once. It is like the token never get refreshed.

**Comment by dvaeversted** [comment]
The initial issued access token is valid for 1 full day as of this writing, and the refresh token for 3 months.

Are you sure you are implementing the `\OnPay\TokenStorageInterface` as described here: https://github.com/onpayio/php-sdk#using-the-api ?

**Comment by JeppeDonslund** [comment]
I have used the code in the link.

It works for 24 hours. Maybe the redirect_uri is wrong. Shouldn't it be to the same file or should it be another file?

**Comment by dvaeversted** [comment]
There is nothing that will cause it to expire after 24 hours, i am unsure of what is going wrong since it is not working for you.

However the code provided is an example, and should be adapted to usage in your own project. Maybe storing the data in the database or somewhere else.
