### ISSUE TITLE
Help in setting up

### ISSUE THREAD

**Issue by RidaNoor** [onpayio/php-sdk#33]
Hey, 
I want to use windows/checkout method of onPay. 
I need to use that in Bagisto. However, I am confused that if I want to use the Windows method, do I still need to install the package? or can I just put the form provided by onPay for windows method and everything will be handled automatically?
Because, if that form is enough to redirect and then the user can perform payment there, then I don't think there is any need to install onPay in my project, right?

**Comment by dvaeversted** [comment]
You will need to use the package, or implement the method for calculating the correct hmac to set in the `onpay_hmac_sha1` field.

Take a look here for details on how to construct the form: https://manage.onpay.io/docs/paymentwindow_v3.html

**Comment by RidaNoor** [comment]
@dvaeversted  Thanks!

Just for the clarification, if I just calculate thus onpay_hmac_sha1, then I don't need to install the package, right?

**Comment by dvaeversted** [comment]
Correct, there is a small PHP implementation on calculating it in the documentation here: https://manage.onpay.io/docs/paymentwindow_v3.html#sha1-hmac-calculation

**Comment by RidaNoor** [comment]
@dvaeversted you're the best.
One more thing, please?
What is this secret variable? Is it some kind of secret key associated with my onPay account?

Also, is there any way to test if I have integrated the form correctly in my project before I get credentials and other details of onPay account from my clients?

**Comment by dvaeversted** [comment]
Yes it is a key that is associated with the specific account, can be seen in the management panel or fetched through the API.

I would recommend you reach out to our normal support, to see if they can provide you with a test account to validate your integration.

**Comment by RidaNoor** [comment]
I tried searching for your normal support but couldn't find the link...

**Comment by dvaeversted** [comment]
It depends on where the product has been bought, see a list of some of the providers here: https://onpay.io/#brands

**Comment by RidaNoor** [comment]
You're the best, thanks! @dvaeversted
