### ISSUE TITLE
Redirection gives error

### ISSUE THREAD

**Issue by RidaNoor** [onpayio/php-sdk#35]
Hi, 
I am using onPay redirection inside Bagisto eCommerce (Laravel PHP) project. 
I using a form and passing all the mandatory input fields to the https://www.onpay.io/window/v3/.
However, when the redirection happens, it gives me error: 

Invalid input
The input data was invalid.
Invalid gateway id or HMAC

Also, in the Console tab, I see the following error: 
Unrecognized Content-Security-Policy directive 'reflected-xss'.

Are they relatable? How can I confirm that my input data is correct? There seem no way to check if the HMAC is correct and I can assure that the gatway id is correct.

**Comment by RidaNoor** [comment]
Also, should I generate a separate HMAC for every request?
Because if I understand this correctly then the onpay_reference is a random but unique string for each call, right?
So using that unique random reference we might need to generate a unique HMAC for every call, am I right?

**Comment by RidaNoor** [comment]
And for generating onpay_reference, I am using Str::random(10) function of PHP to generate a random string of length 10

**Comment by dvaeversted** [comment]
Yes the onpay_hmac has to be calculated each time.

onpay_reference should be set to for example the order id from the shop.

**Comment by RidaNoor** [comment]
@dvaeversted few more things please?
As now it says that input is invalid, how can I know where the things are wrong?

Another thing is, can I pass Tax, Discount and other such prices and values to onPay? Because they are crucial for actual payment and also for invoice

**Comment by dvaeversted** [comment]
Usage support of the OnPay platform should be directed at the support available from the vendor that you are buying the product from.
