### ISSUE TITLE
Support API token when using the SDK

### ISSUE THREAD

**Issue by lucasRolff** [onpayio/php-sdk#47]
I'd love the possibility to be able to use the API token from the OnPay dashboard as a way of communicating with the API via the SDK instead of having to deal with OAuth.

```php
$onPayAPI = new \OnPay\OnPayAPI($tokenStorage, [
    'client_id' => 'example.com', // It is recommended to set it to the domain name the integration resides on
    'redirect_uri' => 'http://localhost/onpay-php-sdk/example2.php?auth',
    'gateway_id' => '1234', // Should be set to the gateway id you are integrating with
]);
```

There could be an option to switch from OAuth to Bearer tokens in the above code for example.

I'll use the Guzzle client for now as a workaround :)

**Comment by ebbesmoeller** [comment]
We have recently added the ability to use static tokens (created in OnPay Manage) with the SDK: https://github.com/onpayio/php-sdk/pull/44

This is done with the StaticToken object: https://github.com/onpayio/php-sdk/blob/master/src/StaticToken.php
Like this:

```php
$accessToken = 'eyJ0eXAiOiJKV1QiLCJ...';
$staticToken = new \OnPay\StaticToken($accessToken);
$onPayAPI = new \OnPay\OnPayAPI($staticToken, [
    'client_id' => 'example.com',
]);
```

**Comment by lucasRolff** [comment]
Perfect, I couldn't immediately see that being a possibility by looking at the construct function of the `OnPayAPI` class ^_^ oh well, thanks a lot!

**Comment by lucasRolff** [comment]
That apparently doesn't seem to work as expected. If doing something like this:

```php
        $api_key = 'ey...';

	$staticToken = new \OnPay\StaticToken($api_key);
	$onPayAPI = new \OnPay\OnPayAPI($staticToken, [
	        'client_id' => 'onpay-integration.test'
    ]);

	$response = $onPayAPI->transaction()->captureTransaction($onpay_number_transaction);

    var_dump($response);die;
```

The result being: 

```
#0 /Users/LucasRolff/Projects/onpay-integration/vendor/onpayio/php-sdk/src/OnPayAPI.php(144): flight\Engine->handleError(8, 'Undefined index...', '/Users/LucasRol...', 144, Array)
#1 /Users/LucasRolff/Projects/onpay-integration/vendor/onpayio/php-sdk/src/OnPayAPI.php(247): OnPay\OnPayAPI->getClient()
#2 /Users/LucasRolff/Projects/onpay-integration/vendor/onpayio/php-sdk/src/API/TransactionService.php(79): OnPay\OnPayAPI->post('transaction/105...')
#3 /Users/LucasRolff/Projects/onpay-integration/index.php(66): OnPay\API\TransactionService->captureTransaction('1055')
```

**Comment by ebbesmoeller** [comment]
This bug has now been addressed in: https://github.com/onpayio/php-sdk/pull/48

**Comment by ebbesmoeller** [comment]
And a new release with this fix is available: https://github.com/onpayio/php-sdk/releases/tag/1.0.16
